name: Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pip, setuptools, and wheel
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install lightfm without PEP 517
      run: pip install --no-use-pep517 lightfm

    - name: Remove lightfm from requirements
      run: grep -v 'lightfm' requirements.txt > requirements_no_lightfm.txt

    - name: Install other dependencies
      run: pip install -r requirements_no_lightfm.txt

    - name: Set environment variables
      run: |
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "SQS_QUEUE_URL=${{ secrets.SQS_QUEUE_URL }}" >> $GITHUB_ENV

    - name: Run tests
      run: pytest